services:
  weather-prediction-api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: weather-prediction-api
    ports:
      - "8001:8000" # Map port 8000 in the container to 8001 on the host
    volumes:
      - ./api:/app/api
      - ./models:/app/models
    deploy:
      resources:
        reservations:
          memory: "128M"
    # restart: unless-stopped

  build-models:
    build:
      context: .
      dockerfile: src/Dockerfile
    environment:
      REDIVIS_API_TOKEN: ${REDIVIS_API_TOKEN}
    container_name: build-models
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./src:/app/src
    restart: "no"
    deploy:
      resources:
        limits:
          cpus: "0.25" # Limit to 25% of a single CPU
          memory: "256M" # Limit memory to 256 MB
