services:
  weather-prediction-api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: weather-prediction-api
    restart: "no"
    ports:
      - "9000:8000" # Map port 8000 in the container to 9000 on the host
    volumes:
      - ./models:/app/models

  build-models:
    build:
      context: .
      dockerfile: src/Dockerfile
    environment:
      REDIVIS_API_TOKEN: ${REDIVIS_API_TOKEN}
    container_name: build-models
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./src:/app/src
    restart: "no"
