name: Backend Deployment

on:
  push:
    paths:
      - "api/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          cd api
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Deploy Backend
        run: |
          echo "Deploying backend..."
          # Add your backend deployment commands here
